[workspace]
members = ["src-tauri"]

# fix: mac v1.2.0 can not copy/paste
# https://github.com/tauri-apps/tauri/issues/5669
[profile.release]
strip = true
lto = true
opt-level = "s"

[patch.crates-io]
 wry = { git = "https://github.com/paulzql/wry.git", branch = "0.24.1-patch" }