name: Release CI

on:
  workflow_dispatch:

jobs:
  build-chatgpt:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: windows
            os: windows-latest
            arch: x86_64
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: 'Setup Rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build FE
        run: pnpm build:fe

      - name: Install rust target
        run: rustup target add ${{ matrix.target }}

      - name: fix tray icon
        if: matrix.os != 'macos-latest'
        run: |
          pnpm fix:tray
      - name: update deps
        run: cargo update

      - run: pnpm build --target ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: "dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5RWhhbVlpVnFtajR2aDJ5S29zRFJYQzVwYWZDdDhqcm1iMFZtc0NVOHlQc0FBQkFBQUFBQUFBQUFBQUlBQUFBQS82QnprSUxQWU5BT0p0RVR1MThEZFpjdHRZVVMzZmpULy80RUE1bXlhQVJEYjE3R0JtSlowQkw3bEFwMHFWNGNRVVp5amlHL215TjF2dXVkTjBXL0dmY0xnR0ZFaWZ5Z2pRUlBmRzI0eUgxeG0razh4UUJELzNPTERWQVFjcVpaVUFrVE93d1p5V3M9Cg=="
          TAURI_KEY_PASSWORD: ""

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: artifacts-${{ matrix.arch }}
          path: |
            ./target/${{ matrix.target }}/release/bundle/msi/**

